name: Gatsby Publish

on:
  push:
    branches:
      [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: pages
          gatsby-args: --prefix-paths
        env:
          NODE_ENV: production
          GATSBY_ACTIVE_ENV: production
      - run: npm run test:int
        env:
          CI: true
